# ===============
# lang
# ===============

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_post_source = '''
    let g:rustfmt_autosave = 1
    let g:rustfmt_options = 'override'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_post_source = '''
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_types = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_extra_types = 1
'''

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'
